"""empty message

Revision ID: 0a1a035ad59c
Revises: 
Create Date: 2023-05-01 19:32:42.923359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1a035ad59c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=150), nullable=True))

    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
